import pygame

WIDTH = 800
HEIGHT = 600
DESIRED_FPS = 30
SCREENRECT = pygame.Rect(0, 0, WIDTH, HEIGHT)
NUM_LANES = 3
LANE_GAP = 10
LANE_WIDTH = 50
TOTAL_WIDTH = NUM_LANES * LANE_WIDTH + (NUM_LANES - 1) * LANE_GAP
START_X = (WIDTH - TOTAL_WIDTH) // 2
LANE_POSITIONS = [START_X + i * (LANE_WIDTH + LANE_GAP) for i in range(NUM_LANES)]
TRAIN_HEIGHTS = [200, 300, 400]
START_Y = -1 * max(TRAIN_HEIGHTS)
SCROLL_SPEED = 4
COIN_GAP = 20
NUM_COINS = 3