import pygame

WIDTH = 800
HEIGHT = 600
DESIRED_FPS = 60
SCREENRECT = pygame.Rect(0, 0, WIDTH, HEIGHT)
NUM_LANES = 3
LANE_GAP = 10
LANE_WIDTH = 50
TOTAL_WIDTH = NUM_LANES * LANE_WIDTH + (NUM_LANES - 1) * LANE_GAP
